// This file contains the default values and configs for the form fields

// Default fields
export const defaultInstFields = {
  InsSerialNum: "",
  BuildID: "",
  TestSheet: "",
  COM: "",
  DOM: "",
  TestingDoneBy: "",
  Model_Num: "",
  ApprovedBy: "",
  ApprovedDate: "",
  SiteLocation: "",
  SiteName: "",
  WarrantyConclusionDate: "",
  Comments: "",
};

export const defaultServData = {
  InsSerialNum: "",
  SRIdentifier: "",
  CaseNum: "",
  CaseType: "",
  Technician: "",
  ServiceDate: "",
  ServiceDurationHrs: 0,
  FieldEvaluationNotes: "",
  ServiceDescription: "",
  FollowupNotes: "",
  PerformanceRptNum: 0,
  Comments: "",
};

// Field configurations for the form
export const instFieldsList = [
  "InsSerialNum",
  "BuildID",
  "TestSheet",
  "COM",
  "DOM",
  "TestingDoneBy",
  "Model_Num",
  "ApprovedBy",
  "ApprovedDate",
  "SiteLocation",
  "SiteName",
  "WarrantyConclusionDate",
  "Comments",
];
export const instConfigs = {
  InsSerialNum: {
    htmlFor: "InsSerialNum",
    label: "Serial Number",
    type: "text",
    id: "InsSerialNum",
    name: "InsSerialNum",
  },
  BuildID: {
    htmlFor: "BuildID",
    label: "Build ID",
    type: "text",
    id: "BuildID",
    name: "BuildID",
  },
  TestSheet: {
    htmlFor: "TestSheet",
    label: "Link to Test Sheet",
    type: "text",
    id: "TestSheet",
    name: "TestSheet",
  },
  COM: {
    htmlFor: "COM",
    label: "Certificate of Manufacture",
    type: "text",
    id: "COM",
    name: "COM",
  },
  DOM: {
    htmlFor: "DOM",
    label: "Date of Manufacture",
    type: "date",
    id: "DOM",
    name: "DOM",
  },
  TestingDoneBy: {
    htmlFor: "TestingDoneBy",
    label: "Testing Done By",
    type: "text",
    id: "TestingDoneBy",
    name: "TestingDoneBy",
  },
  Model_Num: {
    htmlFor: "ModelNum",
    label: "Model Number",
    type: "text",
    id: "ModelNum",
    name: "ModelNum",
  },
  ApprovedBy: {
    htmlFor: "ApprovedBy",
    label: "Approved By",
    type: "text",
    id: "ApprovedBy",
    name: "ApprovedBy",
  },
  ApprovedDate: {
    htmlFor: "ApprovedDate",
    label: "Approved Date",
    type: "date",
    id: "ApprovedDate",
    name: "ApprovedDate",
  },
  SiteLocation: {
    htmlFor: "SiteLocation",
    label: "Site Location",
    type: "text",
    id: "SiteLocation",
    name: "SiteLocation",
  },
  SiteName: {
    htmlFor: "SiteName",
    label: "Site Name",
    type: "text",
    id: "SiteName",
    name: "SiteName",
  },
  WarrantyConclusionDate: {
    htmlFor: "WarrantyConclusionDate",
    label: "Warranty Conclusion Date",
    type: "date",
    id: "WarrantyConclusionDate",
    name: "WarrantyConclusionDate",
  },
  Comments: {
    htmlFor: "comments",
    label: "Comments",
    type: "text",
    id: "comments",
    name: "comments",
  },
};

export const servFieldsList = [
  "InsSerialNum",
  "SRIdentifier",
  "CaseNum",
  "CaseType",
  "Technician",
  "ServiceDate",
  "ServiceDurationHrs",
  "BOM_Update",
  "FieldEvaluationNotes",
  "ServiceDescription",
  "FollowupNotes",
  "PerformanceRptNum",
  "Comments",
];
export const servConfigs = {
  InsSerialNum: {
    htmlFor: "InsSerialNum",
    label: "Instrument Serial Number",
    type: "text",
    id: "InsSerialNum",
    name: "InsSerialNum",
  },
  SRIdentifier: {
    htmlFor: "SRIdentifier",
    label: "Service Record Identifier",
    type: "text",
    id: "SRIdentifier",
    name: "SRIdentifier",
  },
  CaseNum: {
    htmlFor: "CaseNum",
    label: "Case Number",
    type: "text",
    id: "CaseNum",
    name: "CaseNum",
  },
  CaseType: {
    htmlFor: "CaseType",
    label: "Case Type",
    type: "text",
    id: "CaseType",
    name: "CaseType",
  },
  Technician: {
    htmlFor: "Technician",
    label: "Technician",
    type: "text",
    id: "Technician",
    name: "Technician",
  },
  ServiceDate: {
    htmlFor: "ServiceDate",
    label: "Service Date",
    type: "date",
    id: "ServiceDate",
    name: "ServiceDate",
  },
  ServiceDurationHrs: {
    htmlFor: "ServiceDurationHrs",
    label: "Service Duration (Hours)",
    type: "number",
    id: "ServiceDurationHrs",
    name: "ServiceDurationHrs",
  },
  BOM_Update: {
    htmlFor: "BOM_Update",
    label: "BOM Update",
    type: "text",
    id: "BOM_Update",
    name: "BOM_Update",
  },
  FieldEvaluationNotes: {
    htmlFor: "FieldEvaluationNotes",
    label: "Field Evaluation Notes",
    type: "text",
    id: "FieldEvaluationNotes",
    name: "FieldEvaluationNotes",
  },
  ServiceDescription: {
    htmlFor: "ServiceDescription",
    label: "Service Description",
    type: "text",
    id: "ServiceDescription",
    name: "ServiceDescription",
  },
  FollowupNotes: {
    htmlFor: "FollowupNotes",
    label: "Follow-up Notes",
    type: "text",
    id: "FollowupNotes",
    name: "FollowupNotes",
  },
  PerformanceRptNum: {
    htmlFor: "PerformanceRptNum",
    label: "Performance Report Number",
    type: "number",
    id: "PerformanceRptNum",
    name: "PerformanceRptNum",
  },
  Comments: {
    htmlFor: "Comments",
    label: "Comments",
    type: "text",
    id: "Comments",
    name: "Comments",
  },
};
